/**
 * Products Management API
 * This API exposes endpoints to manage items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: busher@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address { 
    id?: number;
    addressLine1?: string;
    addressLine2?: string;
    city?: string;
    country?: string;
}

