/**
 * Products Management API
 * This API exposes endpoints to manage items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: busher@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Inventory } from './inventory';


export interface Product { 
    id?: number;
    name?: string;
    shortDescription?: string;
    longDescription?: string;
    price?: number;
    inventory?: Inventory;
}

